version: '3.8'
services:
  app:
    image: parkjungyu26/kau-capstone:latest
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
